[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "/bin/sh -c \"streamlit run src/Gui/app.py --server.port $PORT --server.address 0.0.0.0\""
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
